# Generated by Django 2.0.7 on 2018-07-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_vierws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='vierws',
            new_name='views',
        ),
    ]
